riconuts/FNF-Troll-Engine

hmm.json, setup/install_haxelibs.bat
I don't think this needs much explanation.
=> Update hxvlc version.

source/funkin/FNFGame.hx, source/funkin/macros/StateScriptingMacro.hx, source/funkin/scripts/FunkinHScript.hx, source/funkin/scripts/Macro.hx, source/funkin/states/MusicBeatState.hx, source/funkin/states/MusicBeatSubstate.hx, source/funkin/states/import.hx, source/funkin/states/scripting/HScriptOverridenState.hx, source/funkin/states/scripting/HScriptedState.hx, source/funkin/states/scripting/HScriptedSubstate.hx, source/funkin/states/scripting/OldHScriptedState.hx, source/funkin/states/scripting/OldHScriptedSubstate.hx
- tl;dr: hscripted states are now to be written the same way as hscript state extension
- state override/extension scripts must now be named after the full class path
- some organization too, and whatever else was necessary to make all of this possible
- each commit mentions their respective changes blah blah yolo merging this
=> Hscripted states improvements

source/funkin/objects/playfields/NoteField.hx
Title says it.
And I tested it with my own spritesheet, 6 different subdiv settings, and optimize holds both on and off
I'd go more in detail but it's super late for me so gn
=> Fix rotated frames on notefield

source/flixel/FlxCamera.hx, source/flixel/FlxSprite.hx, source/flixel/graphics/tile/FlxDrawBaseItem.hx, source/flixel/graphics/tile/FlxDrawQuadsItem.hx, source/flixel/graphics/tile/FlxDrawTilesItem.hx, source/flixel/graphics/tile/FlxDrawTrianglesItem.hx, source/funkin/objects/NoteObject.hx, source/funkin/states/editors/ChartingState.hx
istg if i have to start having to make "whoopsie doodle" commits to an engine that I only work on by pull requesting
=> Allow NoteColorSwap on all draw items (Also fixes ChartingState)

source/funkin/objects/hud/PsychHUD.hx
insert angry dog barking at brick wall here
=> Fix PsychHUD crashing when judgment counters are disabled

Project.xml, source/funkin/ClientPrefs.hx
Fix the framerate issue by using 60 instead of refresh rate
Lua works yay
=> Fix some linux stuff

source/funkin/objects/playfields/NoteField.hx
nebula was a bit upsetti when i got this working.
NOTE: the testing for this wasn't plentiful.
=> allow frame offsets in drawNote

assets/events/Change Stage.hscript
yeah for some reason this class just isn't imported?
=> Fix change stage script

Project.xml
unless mac was added back when it was an issue in ye olde psych, but now that luajit is fine on all platforms its no longer an issue.
=> Remove unless="mac" from LUA_ALLOWED

source/funkin/states/options/OptionsSubstate.hx
made a Tab class and Dropdown class
mainly rewrote the dropdowns to improve/fix some issues with them
thats basically it, the other commits are very minor changes i think
=> OptionsSubstate stuff

assets/data/credits.txt, source/funkin/data/Stats.hx, source/funkin/objects/hud/BaseHUD.hx, source/funkin/objects/hud/CommonHUD.hx, source/funkin/objects/hud/KadeHUD.hx, source/funkin/states/PlayState.hx, source/funkin/states/options/ComboPositionSubstate.hx, source/funkin/states/options/NoteOffsetState.hx
- judgement position menu improvements
- some blanket fixes for noteoffsetstate (should be improved upon later, characters here are also still bugged lol)
some other small shit
- song name pref for timer uses metadata titles
- world judgement combo's offset isn't fugly no more
- WF and SDA aren't used with epics off
=> judgement position menu fixes (some temp) and other stuff

source/funkin/ClientPrefs.hx
So this just magically decided to break after it got merged for some reason?
=> Fix linux building

Project.xml, source/funkin/api/Discord.hx, source/funkin/objects/IndependentVideoSprite.hx
i dont have to switch to a random version every time i wanna build this now yay
=> support newer hxvlc and hxdiscord_rpc

Project.xml, hmm.json, setup/unix-haxelibs.sh, setup/windows-haxelibs.bat, source/flixel/FlxCamera.hx, source/flixel/sound/FlxSound.hx, source/flixel/sound/FlxSoundGroup.hx, source/flixel/system/frontEnds/SoundFrontEnd.hx, source/flixel/tweens/FlxTween.hx, source/flixel/tweens/misc/FlickerTween.hx, source/funkin/states/options/OptionsSubstate.hx
i think a fork would've made this a lot quicker but too lateeeeeeeeee burppppp
=> new flixel shit

README.md
I would rather not use the shitter version of my already shitty name lol
=> Change my name lol

source/funkin/objects/playfields/FieldBase.hx, source/funkin/objects/playfields/NoteField.hx, source/funkin/objects/playfields/NotefieldRenderer.hx, source/funkin/objects/proxies/ProxyField.hx
not a big description to this, not highly tested (still tested), but hey, at least ProxyField doesn't crash now.
=> less hardcoded notefield getting

source/funkin/objects/hud/KadeHUD.hx
- judge counter is more accurate (to 1.8 technically, but still)
- difficulty name is still present on the watermark when time display is set to song name
=> some kade hud tweaks

setup/unix-haxelibs.sh, setup/windows-haxelibs.bat
i don't have commit perms so this is a pr oh well
i had to add this so i could build properly yippee
=> add flxanimate to the setup files

source/funkin/states/editors/CharacterEditorState.hx
Adds a "Current Character" option to the character ghost list dropdown, when selected, the ghost will copy animations and offsets of the currently edited character.
https://github.com/user-attachments/assets/7ba4ef1a-74d9-4d55-822f-a4b457c26d59
closes #134
=> Add the ability for the ghost to mirror the main character

source/funkin/api/Memory.hx, source/funkin/api/build.xml, source/funkin/api/include/memory.h, source/openfl/display/FPS.hx
original c code by David Robert Nadeau
also adds a memory peak counter but idk if you want that so just say if you dont lol
=> use c code to get an accurate memory counter

assets/notetypes/Roll.hscript
changes rolls so characters will react to every key press, rather than singing like they would a regular hold.
idk this feels more visually responsive to player input
=> visual roll improvement
